name: Train Model Only

on:
  workflow_dispatch:  # Bisa dijalankan manual dari GitHub UI

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: clothes-env
          environment-file: MLproject/conda.yaml
          auto-activate-base: false

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy scikit-learn mlflow dagshub joblib

      - name: Set MLflow Tracking Env
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/farisgp/Eksperimen_SML_FarisGhina.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run modelling.py
        run: |
          cd MLproject
          python modelling.py --data_path clothes_price_prediction_preprocessing.csv

      - name: Upload model.pkl
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLproject/model.pkl
